export const directory: Record<string, string> = {
  "h2_learn/functions/concepts/intervals/theory":
    "h2-1_h2_learn/01_functions/01_concepts/01_intervals/01_theory",
  "h2_learn/functions/concepts/intervals/practice":
    "h2-1_h2_learn/01_functions/01_concepts/01_intervals/02_practice",
  "h2_learn/functions/concepts/domain-and-range/theory":
    "h2-1_h2_learn/01_functions/01_concepts/02_domain-and-range/01_theory",
  "h2_learn/functions/concepts/domain-and-range/practice-1":
    "h2-1_h2_learn/01_functions/01_concepts/02_domain-and-range/02_practice-1",
  "h2_learn/functions/concepts/domain-and-range/practice-2":
    "h2-1_h2_learn/01_functions/01_concepts/02_domain-and-range/02_practice-2",
  "h2_learn/functions/inverse/existence/theory":
    "h2-1_h2_learn/01_functions/02_inverse/01_existence/01_theory",
  "h2_learn/functions/inverse/existence/practice":
    "h2-1_h2_learn/01_functions/02_inverse/01_existence/02_practice",
  "h2_learn/functions/inverse/domain/theory":
    "h2-1_h2_learn/01_functions/02_inverse/02_domain/01_theory",
  "h2_learn/functions/inverse/domain/practice":
    "h2-1_h2_learn/01_functions/02_inverse/02_domain/02_practice",
  "h2_learn/functions/inverse/formula/theory":
    "h2-1_h2_learn/01_functions/02_inverse/03_formula/01_theory",
  "h2_learn/functions/inverse/formula/practice":
    "h2-1_h2_learn/01_functions/02_inverse/03_formula/02_practice",
  "h2_learn/functions/inverse/restriction/theory":
    "h2-1_h2_learn/01_functions/02_inverse/04_restriction/01_theory",
  "h2_learn/functions/inverse/restriction/practice":
    "h2-1_h2_learn/01_functions/02_inverse/04_restriction/02_practice",
  "h2_learn/functions/inverse/relationship/theory":
    "h2-1_h2_learn/01_functions/02_inverse/05_relationship/01_theory",
  "h2_learn/functions/inverse/relationship/practice-1":
    "h2-1_h2_learn/01_functions/02_inverse/05_relationship/02_practice-1",
  "h2_learn/functions/inverse/relationship/practice-2":
    "h2-1_h2_learn/01_functions/02_inverse/05_relationship/02_practice-2",
  "h2_learn/functions/composite/existence/theory":
    "h2-1_h2_learn/01_functions/03_composite/01_existence/01_theory",
  "h2_learn/functions/composite/existence/practice":
    "h2-1_h2_learn/01_functions/03_composite/01_existence/02_practice",
  "h2_learn/functions/composite/formula/theory":
    "h2-1_h2_learn/01_functions/03_composite/02_formula/01_theory",
  "h2_learn/functions/composite/formula/practice":
    "h2-1_h2_learn/01_functions/03_composite/02_formula/02_practice",
  "h2_learn/functions/composite/range/theory":
    "h2-1_h2_learn/01_functions/03_composite/03_range/01_theory",
  "h2_learn/functions/composite/range/practice":
    "h2-1_h2_learn/01_functions/03_composite/03_range/02_practice",
  "h2_learn/functions/composite/self-compose/theory":
    "h2-1_h2_learn/01_functions/03_composite/04_self-compose/01_theory",
  "h2_learn/functions/composite/self-compose/practice":
    "h2-1_h2_learn/01_functions/03_composite/04_self-compose/02_practice",
  "h2_learn/functions/composite/compose-inverse/theory":
    "h2-1_h2_learn/01_functions/03_composite/05_compose-inverse/01_theory",
  "h2_learn/functions/composite/compose-inverse/practice":
    "h2-1_h2_learn/01_functions/03_composite/05_compose-inverse/02_practice",
  "h2_learn/functions/more/self-inverse/theory":
    "h2-1_h2_learn/01_functions/04_more/01_self-inverse/01_theory",
  "h2_learn/functions/more/self-inverse/practice":
    "h2-1_h2_learn/01_functions/04_more/01_self-inverse/02_practice",
  "h2_learn/functions/more/piecewise/theory":
    "h2-1_h2_learn/01_functions/04_more/02_piecewise/01_theory",
  "h2_learn/functions/more/piecewise/practice":
    "h2-1_h2_learn/01_functions/04_more/02_piecewise/02_practice",
  "h2_learn/functions/more/modulus/theory":
    "h2-1_h2_learn/01_functions/04_more/03_modulus/01_theory",
  "h2_learn/functions/more/modulus/practice":
    "h2-1_h2_learn/01_functions/04_more/03_modulus/02_practice",
  "h2_learn/functions/more/discriminant/theory":
    "h2-1_h2_learn/01_functions/04_more/04_discriminant/01_theory",
  "h2_learn/functions/more/discriminant/practice":
    "h2-1_h2_learn/01_functions/04_more/04_discriminant/02_practice",
  "h2_learn/graphs-and-transformations/standard-graphs/asymptotes/theory":
    "h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/01_asymptotes/01_theory",
  "h2_learn/graphs-and-transformations/standard-graphs/asymptotes/practice":
    "h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/01_asymptotes/02_practice",
  "h2_learn/graphs-and-transformations/standard-graphs/rational-functions/theory":
    "h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/02_rational-functions/01_theory",
  "h2_learn/graphs-and-transformations/standard-graphs/rational-functions/practice-1":
    "h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/02_rational-functions/02_practice-1",
  "h2_learn/graphs-and-transformations/standard-graphs/rational-functions/practice-2":
    "h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/02_rational-functions/02_practice-2",
  "h2_learn/graphs-and-transformations/standard-graphs/oblique-asymptotes/theory":
    "h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/03_oblique-asymptotes/01_theory",
  "h2_learn/graphs-and-transformations/standard-graphs/oblique-asymptotes/practice-1":
    "h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/03_oblique-asymptotes/02_practice-1",
  "h2_learn/graphs-and-transformations/standard-graphs/oblique-asymptotes/practice-2":
    "h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/03_oblique-asymptotes/02_practice-2",
  "h2_learn/graphs-and-transformations/standard-graphs/more/theory":
    "h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/04_more/01_theory",
  "h2_learn/graphs-and-transformations/standard-graphs/more/practice-1":
    "h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/04_more/02_practice-1",
  "h2_learn/graphs-and-transformations/standard-graphs/more/practice-2":
    "h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/04_more/02_practice-2",
  "h2_learn/graphs-and-transformations/conics/introduction/theory":
    "h2-1_h2_learn/02_graphs-and-transformations/02_conics/01_introduction/01_theory",
  "h2_learn/graphs-and-transformations/conics/introduction/practice":
    "h2-1_h2_learn/02_graphs-and-transformations/02_conics/01_introduction/02_practice",
  "h2_learn/graphs-and-transformations/conics/ellipses/theory":
    "h2-1_h2_learn/02_graphs-and-transformations/02_conics/02_ellipses/01_theory",
  "h2_learn/graphs-and-transformations/conics/ellipses/practice":
    "h2-1_h2_learn/02_graphs-and-transformations/02_conics/02_ellipses/02_practice",
  "h2_learn/graphs-and-transformations/conics/hyperbola/theory":
    "h2-1_h2_learn/02_graphs-and-transformations/02_conics/03_hyperbola/01_theory",
  "h2_learn/graphs-and-transformations/conics/hyperbola/practice":
    "h2-1_h2_learn/02_graphs-and-transformations/02_conics/03_hyperbola/02_practice",
  "h2_learn/graphs-and-transformations/conics/completing-the-square/theory":
    "h2-1_h2_learn/02_graphs-and-transformations/02_conics/04_completing-the-square/01_theory",
  "h2_learn/graphs-and-transformations/conics/completing-the-square/practice":
    "h2-1_h2_learn/02_graphs-and-transformations/02_conics/04_completing-the-square/02_practice",
  "h2_learn/graphs-and-transformations/transformations/translation-scaling-reflection/theory":
    "h2-1_h2_learn/02_graphs-and-transformations/03_transformations/01_translation-scaling-reflection/01_theory",
  "h2_learn/graphs-and-transformations/transformations/translation-scaling-reflection/practice":
    "h2-1_h2_learn/02_graphs-and-transformations/03_transformations/01_translation-scaling-reflection/02_practice",
  "h2_learn/graphs-and-transformations/transformations/modulus/theory":
    "h2-1_h2_learn/02_graphs-and-transformations/03_transformations/02_modulus/01_theory",
  "h2_learn/graphs-and-transformations/transformations/modulus/practice":
    "h2-1_h2_learn/02_graphs-and-transformations/03_transformations/02_modulus/02_practice",
  "h2_learn/graphs-and-transformations/transformations/reciprocal/theory":
    "h2-1_h2_learn/02_graphs-and-transformations/03_transformations/03_reciprocal/01_theory",
  "h2_learn/graphs-and-transformations/transformations/reciprocal/practice":
    "h2-1_h2_learn/02_graphs-and-transformations/03_transformations/03_reciprocal/02_practice",
  "h2_learn/graphs-and-transformations/transformations/derivative/theory":
    "h2-1_h2_learn/02_graphs-and-transformations/03_transformations/04_derivative/01_theory",
  "h2_learn/graphs-and-transformations/transformations/derivative/practice":
    "h2-1_h2_learn/02_graphs-and-transformations/03_transformations/04_derivative/02_practice",
};
