export const topics = [
	'Equations and Inequalities',
	'Functions',
	'Graphs and Transformations',
	'Arithmetic and Geometric Progressions (APs, GPs)',
	'Sigma Notation',
	'Differentiation I: Tangents and Normals, Parametric Curves',
	'Differentiation II: Maxima, Minima, Rates of Change',
	'Maclaurin Series',
	'Integration Techniques',
	'Definite Integrals: Areas and Volumes',
	'Differential Equations (DEs)',
	'Vectors I: Basics, Dot and Cross Products',
	'Vectors II: Lines and Planes',
	'Complex Numbers',
	'Permutations and Combinations (P&C)',
	'Probability',
	'Discrete Random Variables (DRVs)',
	'The Binomial Distribution',
	'The Normal Distribution',
	'Sampling Theory',
	'Hypothesis Testing',
	'Linear Correlation and Regression'
];
