// generated by Mathlified on 9/6/2024, 10:40:10 PM
export interface NavNode {
  name: string;
  slug: string;
  fileSlug: string;
  children?: NavNode[];
}
export const h2_learnNav: NavNode = {
  name: "H2_learn",
  slug: "/h2_learn",
  fileSlug: "/h2-1_h2_learn",
  children: [
    {
      name: "Functions",
      slug: "/h2_learn/functions",
      fileSlug: "/h2-1_h2_learn/01_functions",
      children: [
        {
          name: "Concepts",
          slug: "/h2_learn/functions/concepts",
          fileSlug: "/h2-1_h2_learn/01_functions/01_concepts",
          children: [
            {
              name: "Intervals",
              slug: "/h2_learn/functions/concepts/intervals",
              fileSlug: "/h2-1_h2_learn/01_functions/01_concepts/01_intervals",
              children: [
                {
                  name: "Describing sets of real numbers",
                  slug: "/h2_learn/functions/concepts/intervals/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/01_concepts/01_intervals/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/concepts/intervals/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/01_concepts/01_intervals/02_practice",
                },
              ],
            },
            {
              name: "Domain and range",
              slug: "/h2_learn/functions/concepts/domain-and-range",
              fileSlug:
                "/h2-1_h2_learn/01_functions/01_concepts/02_domain-and-range",
              children: [
                {
                  name: "Functions, domain and range",
                  slug: "/h2_learn/functions/concepts/domain-and-range/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/01_concepts/02_domain-and-range/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/concepts/domain-and-range/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/01_concepts/02_domain-and-range/02_practice",
                },
              ],
            },
          ],
        },
        {
          name: "Inverse",
          slug: "/h2_learn/functions/inverse",
          fileSlug: "/h2-1_h2_learn/01_functions/02_inverse",
          children: [
            {
              name: "Existence",
              slug: "/h2_learn/functions/inverse/existence",
              fileSlug: "/h2-1_h2_learn/01_functions/02_inverse/01_existence",
              children: [
                {
                  name: "Existence of inverse functions",
                  slug: "/h2_learn/functions/inverse/existence/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/01_existence/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/inverse/existence/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/01_existence/02_practice",
                },
              ],
            },
            {
              name: "Domain",
              slug: "/h2_learn/functions/inverse/domain",
              fileSlug: "/h2-1_h2_learn/01_functions/02_inverse/02_domain",
              children: [
                {
                  name: "Domain and range of inverse functions",
                  slug: "/h2_learn/functions/inverse/domain/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/02_domain/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/inverse/domain/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/02_domain/02_practice",
                },
              ],
            },
            {
              name: "Formula",
              slug: "/h2_learn/functions/inverse/formula",
              fileSlug: "/h2-1_h2_learn/01_functions/02_inverse/03_formula",
              children: [
                {
                  name: "Formula of inverse functions",
                  slug: "/h2_learn/functions/inverse/formula/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/03_formula/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/inverse/formula/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/03_formula/02_practice",
                },
              ],
            },
            {
              name: "Restriction",
              slug: "/h2_learn/functions/inverse/restriction",
              fileSlug: "/h2-1_h2_learn/01_functions/02_inverse/04_restriction",
              children: [
                {
                  name: "Domain restriction",
                  slug: "/h2_learn/functions/inverse/restriction/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/04_restriction/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/inverse/restriction/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/04_restriction/02_practice",
                },
              ],
            },
            {
              name: "Relationship",
              slug: "/h2_learn/functions/inverse/relationship",
              fileSlug:
                "/h2-1_h2_learn/01_functions/02_inverse/05_relationship",
              children: [
                {
                  name: "Relationship between a function and its inverse",
                  slug: "/h2_learn/functions/inverse/relationship/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/05_relationship/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/inverse/relationship/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/05_relationship/02_practice",
                },
              ],
            },
          ],
        },
        {
          name: "Composite",
          slug: "/h2_learn/functions/composite",
          fileSlug: "/h2-1_h2_learn/01_functions/03_composite",
          children: [
            {
              name: "Existence",
              slug: "/h2_learn/functions/composite/existence",
              fileSlug: "/h2-1_h2_learn/01_functions/03_composite/01_existence",
              children: [
                {
                  name: "Existence of composite functions",
                  slug: "/h2_learn/functions/composite/existence/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/01_existence/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/composite/existence/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/01_existence/02_practice",
                },
              ],
            },
            {
              name: "Formula",
              slug: "/h2_learn/functions/composite/formula",
              fileSlug: "/h2-1_h2_learn/01_functions/03_composite/02_formula",
              children: [
                {
                  name: "Formula and domain of composite functions",
                  slug: "/h2_learn/functions/composite/formula/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/02_formula/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/composite/formula/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/02_formula/02_practice",
                },
              ],
            },
            {
              name: "Range",
              slug: "/h2_learn/functions/composite/range",
              fileSlug: "/h2-1_h2_learn/01_functions/03_composite/03_range",
              children: [
                {
                  name: "Range of composite functions",
                  slug: "/h2_learn/functions/composite/range/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/03_range/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/composite/range/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/03_range/02_practice",
                },
              ],
            },
            {
              name: "Self compose",
              slug: "/h2_learn/functions/composite/self-compose",
              fileSlug:
                "/h2-1_h2_learn/01_functions/03_composite/04_self-compose",
              children: [
                {
                  name: "Self composition",
                  slug: "/h2_learn/functions/composite/self-compose/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/04_self-compose/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/composite/self-compose/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/04_self-compose/02_practice",
                },
              ],
            },
            {
              name: "Compose inverse",
              slug: "/h2_learn/functions/composite/compose-inverse",
              fileSlug:
                "/h2-1_h2_learn/01_functions/03_composite/05_compose-inverse",
              children: [
                {
                  name: "Composing inverse functions",
                  slug: "/h2_learn/functions/composite/compose-inverse/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/05_compose-inverse/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/composite/compose-inverse/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/05_compose-inverse/02_practice",
                },
              ],
            },
          ],
        },
        {
          name: "More",
          slug: "/h2_learn/functions/more",
          fileSlug: "/h2-1_h2_learn/01_functions/04_more",
          children: [
            {
              name: "Self inverse",
              slug: "/h2_learn/functions/more/self-inverse",
              fileSlug: "/h2-1_h2_learn/01_functions/04_more/01_self-inverse",
              children: [
                {
                  name: "Self-inverse functions",
                  slug: "/h2_learn/functions/more/self-inverse/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/04_more/01_self-inverse/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/more/self-inverse/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/04_more/01_self-inverse/02_practice",
                },
              ],
            },
            {
              name: "Piecewise",
              slug: "/h2_learn/functions/more/piecewise",
              fileSlug: "/h2-1_h2_learn/01_functions/04_more/02_piecewise",
              children: [
                {
                  name: "Piecewise functions",
                  slug: "/h2_learn/functions/more/piecewise/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/04_more/02_piecewise/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/more/piecewise/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/04_more/02_piecewise/02_practice",
                },
              ],
            },
            {
              name: "Modulus",
              slug: "/h2_learn/functions/more/modulus",
              fileSlug: "/h2-1_h2_learn/01_functions/04_more/03_modulus",
              children: [
                {
                  name: "Modulus functions",
                  slug: "/h2_learn/functions/more/modulus/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/04_more/03_modulus/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/more/modulus/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/04_more/03_modulus/02_practice",
                },
              ],
            },
            {
              name: "Discriminant",
              slug: "/h2_learn/functions/more/discriminant",
              fileSlug: "/h2-1_h2_learn/01_functions/04_more/04_discriminant",
              children: [
                {
                  name: "Using the quadratic discriminant",
                  slug: "/h2_learn/functions/more/discriminant/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/04_more/04_discriminant/01_theory",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
export const h2_solutionsNav: NavNode = {
  name: "H2_solutions",
  slug: "/h2_solutions",
  fileSlug: "/h2-2_h2_solutions",
  children: [
    {
      name: "2007",
      slug: "/h2_solutions/2007",
      fileSlug: "/h2-2_h2_solutions/2007",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2007/p1",
          fileSlug: "/h2-2_h2_solutions/2007/p1",
          children: [
            {
              name: "Q2",
              slug: "/h2_solutions/2007/p1/q2",
              fileSlug: "/h2-2_h2_solutions/2007/p1/q2",
            },
          ],
        },
      ],
    },
    {
      name: "2008",
      slug: "/h2_solutions/2008",
      fileSlug: "/h2-2_h2_solutions/2008",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2008/p2",
          fileSlug: "/h2-2_h2_solutions/2008/p2",
          children: [
            {
              name: "Q4",
              slug: "/h2_solutions/2008/p2/q4",
              fileSlug: "/h2-2_h2_solutions/2008/p2/q4",
            },
          ],
        },
      ],
    },
    {
      name: "2009",
      slug: "/h2_solutions/2009",
      fileSlug: "/h2-2_h2_solutions/2009",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2009/p2",
          fileSlug: "/h2-2_h2_solutions/2009/p2",
          children: [
            {
              name: "Q3",
              slug: "/h2_solutions/2009/p2/q3",
              fileSlug: "/h2-2_h2_solutions/2009/p2/q3",
            },
          ],
        },
      ],
    },
    {
      name: "2010",
      slug: "/h2_solutions/2010",
      fileSlug: "/h2-2_h2_solutions/2010",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2010/p2",
          fileSlug: "/h2-2_h2_solutions/2010/p2",
          children: [
            {
              name: "Q4",
              slug: "/h2_solutions/2010/p2/q4",
              fileSlug: "/h2-2_h2_solutions/2010/p2/q4",
            },
          ],
        },
      ],
    },
    {
      name: "2011",
      slug: "/h2_solutions/2011",
      fileSlug: "/h2-2_h2_solutions/2011",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2011/p2",
          fileSlug: "/h2-2_h2_solutions/2011/p2",
          children: [
            {
              name: "Q3",
              slug: "/h2_solutions/2011/p2/q3",
              fileSlug: "/h2-2_h2_solutions/2011/p2/q3",
            },
          ],
        },
      ],
    },
    {
      name: "2012",
      slug: "/h2_solutions/2012",
      fileSlug: "/h2-2_h2_solutions/2012",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2012/p1",
          fileSlug: "/h2-2_h2_solutions/2012/p1",
          children: [
            {
              name: "Q7",
              slug: "/h2_solutions/2012/p1/q7",
              fileSlug: "/h2-2_h2_solutions/2012/p1/q7",
            },
          ],
        },
      ],
    },
    {
      name: "2013",
      slug: "/h2_solutions/2013",
      fileSlug: "/h2-2_h2_solutions/2013",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2013/p2",
          fileSlug: "/h2-2_h2_solutions/2013/p2",
          children: [
            {
              name: "Q1",
              slug: "/h2_solutions/2013/p2/q1",
              fileSlug: "/h2-2_h2_solutions/2013/p2/q1",
            },
          ],
        },
      ],
    },
    {
      name: "2014",
      slug: "/h2_solutions/2014",
      fileSlug: "/h2-2_h2_solutions/2014",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2014/p1",
          fileSlug: "/h2-2_h2_solutions/2014/p1",
          children: [
            {
              name: "Q1",
              slug: "/h2_solutions/2014/p1/q1",
              fileSlug: "/h2-2_h2_solutions/2014/p1/q1",
            },
          ],
        },
      ],
    },
    {
      name: "2015",
      slug: "/h2_solutions/2015",
      fileSlug: "/h2-2_h2_solutions/2015",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2015/p2",
          fileSlug: "/h2-2_h2_solutions/2015/p2",
          children: [
            {
              name: "Q3",
              slug: "/h2_solutions/2015/p2/q3",
              fileSlug: "/h2-2_h2_solutions/2015/p2/q3",
            },
          ],
        },
      ],
    },
    {
      name: "2016",
      slug: "/h2_solutions/2016",
      fileSlug: "/h2-2_h2_solutions/2016",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2016/p1",
          fileSlug: "/h2-2_h2_solutions/2016/p1",
          children: [
            {
              name: "Q10",
              slug: "/h2_solutions/2016/p1/q10",
              fileSlug: "/h2-2_h2_solutions/2016/p1/q10",
            },
          ],
        },
      ],
    },
    {
      name: "2017",
      slug: "/h2_solutions/2017",
      fileSlug: "/h2-2_h2_solutions/2017",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2017/p2",
          fileSlug: "/h2-2_h2_solutions/2017/p2",
          children: [
            {
              name: "Q3",
              slug: "/h2_solutions/2017/p2/q3",
              fileSlug: "/h2-2_h2_solutions/2017/p2/q3",
            },
          ],
        },
      ],
    },
    {
      name: "2018",
      slug: "/h2_solutions/2018",
      fileSlug: "/h2-2_h2_solutions/2018",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2018/p1",
          fileSlug: "/h2-2_h2_solutions/2018/p1",
          children: [
            {
              name: "Q5",
              slug: "/h2_solutions/2018/p1/q5",
              fileSlug: "/h2-2_h2_solutions/2018/p1/q5",
            },
          ],
        },
      ],
    },
    {
      name: "2019",
      slug: "/h2_solutions/2019",
      fileSlug: "/h2-2_h2_solutions/2019",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2019/p1",
          fileSlug: "/h2-2_h2_solutions/2019/p1",
          children: [
            {
              name: "Q5",
              slug: "/h2_solutions/2019/p1/q5",
              fileSlug: "/h2-2_h2_solutions/2019/p1/q5",
            },
          ],
        },
      ],
    },
    {
      name: "2021",
      slug: "/h2_solutions/2021",
      fileSlug: "/h2-2_h2_solutions/2021",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2021/p2",
          fileSlug: "/h2-2_h2_solutions/2021/p2",
          children: [
            {
              name: "Q3",
              slug: "/h2_solutions/2021/p2/q3",
              fileSlug: "/h2-2_h2_solutions/2021/p2/q3",
            },
          ],
        },
      ],
    },
    {
      name: "2022",
      slug: "/h2_solutions/2022",
      fileSlug: "/h2-2_h2_solutions/2022",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2022/p1",
          fileSlug: "/h2-2_h2_solutions/2022/p1",
          children: [
            {
              name: "Q6",
              slug: "/h2_solutions/2022/p1/q6",
              fileSlug: "/h2-2_h2_solutions/2022/p1/q6",
            },
          ],
        },
      ],
    },
    {
      name: "2023",
      slug: "/h2_solutions/2023",
      fileSlug: "/h2-2_h2_solutions/2023",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2023/p1",
          fileSlug: "/h2-2_h2_solutions/2023/p1",
          children: [
            {
              name: "Q7",
              slug: "/h2_solutions/2023/p1/q7",
              fileSlug: "/h2-2_h2_solutions/2023/p1/q7",
            },
          ],
        },
      ],
    },
  ],
};
export const h2_learnSequential: { name: string; slug: string }[] = [
  {
    name: "Describing sets of real numbers",
    slug: "/h2_learn/functions/concepts/intervals/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/concepts/intervals/practice" },
  {
    name: "Functions, domain and range",
    slug: "/h2_learn/functions/concepts/domain-and-range/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/functions/concepts/domain-and-range/practice",
  },
  {
    name: "Existence of inverse functions",
    slug: "/h2_learn/functions/inverse/existence/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/inverse/existence/practice" },
  {
    name: "Domain and range of inverse functions",
    slug: "/h2_learn/functions/inverse/domain/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/inverse/domain/practice" },
  {
    name: "Formula of inverse functions",
    slug: "/h2_learn/functions/inverse/formula/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/inverse/formula/practice" },
  {
    name: "Domain restriction",
    slug: "/h2_learn/functions/inverse/restriction/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/functions/inverse/restriction/practice",
  },
  {
    name: "Relationship between a function and its inverse",
    slug: "/h2_learn/functions/inverse/relationship/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/functions/inverse/relationship/practice",
  },
  {
    name: "Existence of composite functions",
    slug: "/h2_learn/functions/composite/existence/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/functions/composite/existence/practice",
  },
  {
    name: "Formula and domain of composite functions",
    slug: "/h2_learn/functions/composite/formula/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/composite/formula/practice" },
  {
    name: "Range of composite functions",
    slug: "/h2_learn/functions/composite/range/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/composite/range/practice" },
  {
    name: "Self composition",
    slug: "/h2_learn/functions/composite/self-compose/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/functions/composite/self-compose/practice",
  },
  {
    name: "Composing inverse functions",
    slug: "/h2_learn/functions/composite/compose-inverse/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/functions/composite/compose-inverse/practice",
  },
  {
    name: "Self-inverse functions",
    slug: "/h2_learn/functions/more/self-inverse/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/more/self-inverse/practice" },
  {
    name: "Piecewise functions",
    slug: "/h2_learn/functions/more/piecewise/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/more/piecewise/practice" },
  {
    name: "Modulus functions",
    slug: "/h2_learn/functions/more/modulus/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/more/modulus/practice" },
  {
    name: "Using the quadratic discriminant",
    slug: "/h2_learn/functions/more/discriminant/theory",
  },
];
export const h2_solutionsSequential: { name: string; slug: string }[] = [
  { name: "Q2", slug: "/h2_solutions/2007/p1/q2" },
  { name: "Q4", slug: "/h2_solutions/2008/p2/q4" },
  { name: "Q3", slug: "/h2_solutions/2009/p2/q3" },
  { name: "Q4", slug: "/h2_solutions/2010/p2/q4" },
  { name: "Q3", slug: "/h2_solutions/2011/p2/q3" },
  { name: "Q7", slug: "/h2_solutions/2012/p1/q7" },
  { name: "Q1", slug: "/h2_solutions/2013/p2/q1" },
  { name: "Q1", slug: "/h2_solutions/2014/p1/q1" },
  { name: "Q3", slug: "/h2_solutions/2015/p2/q3" },
  { name: "Q10", slug: "/h2_solutions/2016/p1/q10" },
  { name: "Q3", slug: "/h2_solutions/2017/p2/q3" },
  { name: "Q5", slug: "/h2_solutions/2018/p1/q5" },
  { name: "Q5", slug: "/h2_solutions/2019/p1/q5" },
  { name: "Q3", slug: "/h2_solutions/2021/p2/q3" },
  { name: "Q6", slug: "/h2_solutions/2022/p1/q6" },
  { name: "Q7", slug: "/h2_solutions/2023/p1/q7" },
];
export const nav = [h2_learnNav, h2_solutionsNav];
export const sequentialNav = [...h2_learnSequential, ...h2_solutionsSequential];
