// generated by Mathlified on 9/17/2024, 6:15:50 PM
export interface NavNode {
  name: string;
  slug: string;
  fileSlug: string;
  children?: NavNode[];
}
export const h2_learnNav: NavNode = {
  name: "H2_learn",
  slug: "/h2_learn",
  fileSlug: "/h2-1_h2_learn",
  children: [
    {
      name: "Functions",
      slug: "/h2_learn/functions",
      fileSlug: "/h2-1_h2_learn/01_functions",
      children: [
        {
          name: "Concepts",
          slug: "/h2_learn/functions/concepts",
          fileSlug: "/h2-1_h2_learn/01_functions/01_concepts",
          children: [
            {
              name: "Intervals",
              slug: "/h2_learn/functions/concepts/intervals",
              fileSlug: "/h2-1_h2_learn/01_functions/01_concepts/01_intervals",
              children: [
                {
                  name: "Describing sets of real numbers",
                  slug: "/h2_learn/functions/concepts/intervals/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/01_concepts/01_intervals/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/concepts/intervals/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/01_concepts/01_intervals/02_practice",
                },
              ],
            },
            {
              name: "Domain and range",
              slug: "/h2_learn/functions/concepts/domain-and-range",
              fileSlug:
                "/h2-1_h2_learn/01_functions/01_concepts/02_domain-and-range",
              children: [
                {
                  name: "Functions, domain and range",
                  slug: "/h2_learn/functions/concepts/domain-and-range/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/01_concepts/02_domain-and-range/01_theory",
                },
                {
                  name: "Practice 1",
                  slug: "/h2_learn/functions/concepts/domain-and-range/practice-1",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/01_concepts/02_domain-and-range/02_practice-1",
                },
                {
                  name: "Practice 2",
                  slug: "/h2_learn/functions/concepts/domain-and-range/practice-2",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/01_concepts/02_domain-and-range/02_practice-2",
                },
              ],
            },
          ],
        },
        {
          name: "Inverse",
          slug: "/h2_learn/functions/inverse",
          fileSlug: "/h2-1_h2_learn/01_functions/02_inverse",
          children: [
            {
              name: "Existence",
              slug: "/h2_learn/functions/inverse/existence",
              fileSlug: "/h2-1_h2_learn/01_functions/02_inverse/01_existence",
              children: [
                {
                  name: "Existence of inverse functions",
                  slug: "/h2_learn/functions/inverse/existence/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/01_existence/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/inverse/existence/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/01_existence/02_practice",
                },
              ],
            },
            {
              name: "Domain",
              slug: "/h2_learn/functions/inverse/domain",
              fileSlug: "/h2-1_h2_learn/01_functions/02_inverse/02_domain",
              children: [
                {
                  name: "Domain and range of inverse functions",
                  slug: "/h2_learn/functions/inverse/domain/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/02_domain/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/inverse/domain/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/02_domain/02_practice",
                },
              ],
            },
            {
              name: "Formula",
              slug: "/h2_learn/functions/inverse/formula",
              fileSlug: "/h2-1_h2_learn/01_functions/02_inverse/03_formula",
              children: [
                {
                  name: "Formula of inverse functions",
                  slug: "/h2_learn/functions/inverse/formula/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/03_formula/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/inverse/formula/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/03_formula/02_practice",
                },
              ],
            },
            {
              name: "Restriction",
              slug: "/h2_learn/functions/inverse/restriction",
              fileSlug: "/h2-1_h2_learn/01_functions/02_inverse/04_restriction",
              children: [
                {
                  name: "Domain restriction",
                  slug: "/h2_learn/functions/inverse/restriction/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/04_restriction/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/inverse/restriction/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/04_restriction/02_practice",
                },
              ],
            },
            {
              name: "Relationship",
              slug: "/h2_learn/functions/inverse/relationship",
              fileSlug:
                "/h2-1_h2_learn/01_functions/02_inverse/05_relationship",
              children: [
                {
                  name: "Relationship between a function and its inverse",
                  slug: "/h2_learn/functions/inverse/relationship/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/05_relationship/01_theory",
                },
                {
                  name: "Practice 1",
                  slug: "/h2_learn/functions/inverse/relationship/practice-1",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/05_relationship/02_practice-1",
                },
                {
                  name: "Practice 2",
                  slug: "/h2_learn/functions/inverse/relationship/practice-2",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/02_inverse/05_relationship/02_practice-2",
                },
              ],
            },
          ],
        },
        {
          name: "Composite",
          slug: "/h2_learn/functions/composite",
          fileSlug: "/h2-1_h2_learn/01_functions/03_composite",
          children: [
            {
              name: "Existence",
              slug: "/h2_learn/functions/composite/existence",
              fileSlug: "/h2-1_h2_learn/01_functions/03_composite/01_existence",
              children: [
                {
                  name: "Existence of composite functions",
                  slug: "/h2_learn/functions/composite/existence/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/01_existence/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/composite/existence/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/01_existence/02_practice",
                },
              ],
            },
            {
              name: "Formula",
              slug: "/h2_learn/functions/composite/formula",
              fileSlug: "/h2-1_h2_learn/01_functions/03_composite/02_formula",
              children: [
                {
                  name: "Formula and domain of composite functions",
                  slug: "/h2_learn/functions/composite/formula/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/02_formula/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/composite/formula/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/02_formula/02_practice",
                },
              ],
            },
            {
              name: "Range",
              slug: "/h2_learn/functions/composite/range",
              fileSlug: "/h2-1_h2_learn/01_functions/03_composite/03_range",
              children: [
                {
                  name: "Range of composite functions",
                  slug: "/h2_learn/functions/composite/range/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/03_range/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/composite/range/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/03_range/02_practice",
                },
              ],
            },
            {
              name: "Self compose",
              slug: "/h2_learn/functions/composite/self-compose",
              fileSlug:
                "/h2-1_h2_learn/01_functions/03_composite/04_self-compose",
              children: [
                {
                  name: "Self composition",
                  slug: "/h2_learn/functions/composite/self-compose/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/04_self-compose/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/composite/self-compose/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/04_self-compose/02_practice",
                },
              ],
            },
            {
              name: "Compose inverse",
              slug: "/h2_learn/functions/composite/compose-inverse",
              fileSlug:
                "/h2-1_h2_learn/01_functions/03_composite/05_compose-inverse",
              children: [
                {
                  name: "Composing inverse functions",
                  slug: "/h2_learn/functions/composite/compose-inverse/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/05_compose-inverse/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/composite/compose-inverse/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/03_composite/05_compose-inverse/02_practice",
                },
              ],
            },
          ],
        },
        {
          name: "More",
          slug: "/h2_learn/functions/more",
          fileSlug: "/h2-1_h2_learn/01_functions/04_more",
          children: [
            {
              name: "Self inverse",
              slug: "/h2_learn/functions/more/self-inverse",
              fileSlug: "/h2-1_h2_learn/01_functions/04_more/01_self-inverse",
              children: [
                {
                  name: "Self-inverse functions",
                  slug: "/h2_learn/functions/more/self-inverse/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/04_more/01_self-inverse/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/more/self-inverse/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/04_more/01_self-inverse/02_practice",
                },
              ],
            },
            {
              name: "Piecewise",
              slug: "/h2_learn/functions/more/piecewise",
              fileSlug: "/h2-1_h2_learn/01_functions/04_more/02_piecewise",
              children: [
                {
                  name: "Piecewise functions",
                  slug: "/h2_learn/functions/more/piecewise/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/04_more/02_piecewise/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/more/piecewise/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/04_more/02_piecewise/02_practice",
                },
              ],
            },
            {
              name: "Modulus",
              slug: "/h2_learn/functions/more/modulus",
              fileSlug: "/h2-1_h2_learn/01_functions/04_more/03_modulus",
              children: [
                {
                  name: "Modulus functions",
                  slug: "/h2_learn/functions/more/modulus/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/04_more/03_modulus/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/more/modulus/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/04_more/03_modulus/02_practice",
                },
              ],
            },
            {
              name: "Discriminant",
              slug: "/h2_learn/functions/more/discriminant",
              fileSlug: "/h2-1_h2_learn/01_functions/04_more/04_discriminant",
              children: [
                {
                  name: "Using the quadratic discriminant",
                  slug: "/h2_learn/functions/more/discriminant/theory",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/04_more/04_discriminant/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/functions/more/discriminant/practice",
                  fileSlug:
                    "/h2-1_h2_learn/01_functions/04_more/04_discriminant/02_practice",
                },
              ],
            },
          ],
        },
      ],
    },
    {
      name: "Graphs and transformations",
      slug: "/h2_learn/graphs-and-transformations",
      fileSlug: "/h2-1_h2_learn/02_graphs-and-transformations",
      children: [
        {
          name: "Standard graphs",
          slug: "/h2_learn/graphs-and-transformations/standard-graphs",
          fileSlug:
            "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs",
          children: [
            {
              name: "Asymptotes",
              slug: "/h2_learn/graphs-and-transformations/standard-graphs/asymptotes",
              fileSlug:
                "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/01_asymptotes",
              children: [
                {
                  name: "Asymptotes",
                  slug: "/h2_learn/graphs-and-transformations/standard-graphs/asymptotes/theory",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/01_asymptotes/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/graphs-and-transformations/standard-graphs/asymptotes/practice",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/01_asymptotes/02_practice",
                },
              ],
            },
            {
              name: "Rational functions",
              slug: "/h2_learn/graphs-and-transformations/standard-graphs/rational-functions",
              fileSlug:
                "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/02_rational-functions",
              children: [
                {
                  name: "Rational functions",
                  slug: "/h2_learn/graphs-and-transformations/standard-graphs/rational-functions/theory",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/02_rational-functions/01_theory",
                },
                {
                  name: "Practice 1",
                  slug: "/h2_learn/graphs-and-transformations/standard-graphs/rational-functions/practice-1",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/02_rational-functions/02_practice-1",
                },
                {
                  name: "Practice 2",
                  slug: "/h2_learn/graphs-and-transformations/standard-graphs/rational-functions/practice-2",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/02_rational-functions/02_practice-2",
                },
              ],
            },
            {
              name: "Oblique asymptotes",
              slug: "/h2_learn/graphs-and-transformations/standard-graphs/oblique-asymptotes",
              fileSlug:
                "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/03_oblique-asymptotes",
              children: [
                {
                  name: "Oblique asymptotes",
                  slug: "/h2_learn/graphs-and-transformations/standard-graphs/oblique-asymptotes/theory",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/03_oblique-asymptotes/01_theory",
                },
                {
                  name: "Practice 1",
                  slug: "/h2_learn/graphs-and-transformations/standard-graphs/oblique-asymptotes/practice-1",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/03_oblique-asymptotes/02_practice-1",
                },
                {
                  name: "Practice 2",
                  slug: "/h2_learn/graphs-and-transformations/standard-graphs/oblique-asymptotes/practice-2",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/03_oblique-asymptotes/02_practice-2",
                },
              ],
            },
            {
              name: "More",
              slug: "/h2_learn/graphs-and-transformations/standard-graphs/more",
              fileSlug:
                "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/04_more",
              children: [
                {
                  name: "Functions, domain and range",
                  slug: "/h2_learn/graphs-and-transformations/standard-graphs/more/theory",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/04_more/01_theory",
                },
                {
                  name: "Practice 1",
                  slug: "/h2_learn/graphs-and-transformations/standard-graphs/more/practice-1",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/04_more/02_practice-1",
                },
                {
                  name: "Practice 2",
                  slug: "/h2_learn/graphs-and-transformations/standard-graphs/more/practice-2",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/01_standard-graphs/04_more/02_practice-2",
                },
              ],
            },
          ],
        },
        {
          name: "Conics",
          slug: "/h2_learn/graphs-and-transformations/conics",
          fileSlug: "/h2-1_h2_learn/02_graphs-and-transformations/02_conics",
          children: [
            {
              name: "Introduction",
              slug: "/h2_learn/graphs-and-transformations/conics/introduction",
              fileSlug:
                "/h2-1_h2_learn/02_graphs-and-transformations/02_conics/01_introduction",
              children: [
                {
                  name: "Existence of inverse functions",
                  slug: "/h2_learn/graphs-and-transformations/conics/introduction/theory",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/02_conics/01_introduction/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/graphs-and-transformations/conics/introduction/practice",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/02_conics/01_introduction/02_practice",
                },
              ],
            },
            {
              name: "Ellipses",
              slug: "/h2_learn/graphs-and-transformations/conics/ellipses",
              fileSlug:
                "/h2-1_h2_learn/02_graphs-and-transformations/02_conics/02_ellipses",
              children: [
                {
                  name: "Domain and range of inverse functions",
                  slug: "/h2_learn/graphs-and-transformations/conics/ellipses/theory",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/02_conics/02_ellipses/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/graphs-and-transformations/conics/ellipses/practice",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/02_conics/02_ellipses/02_practice",
                },
              ],
            },
            {
              name: "Hyperbola",
              slug: "/h2_learn/graphs-and-transformations/conics/hyperbola",
              fileSlug:
                "/h2-1_h2_learn/02_graphs-and-transformations/02_conics/03_hyperbola",
              children: [
                {
                  name: "Formula of inverse functions",
                  slug: "/h2_learn/graphs-and-transformations/conics/hyperbola/theory",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/02_conics/03_hyperbola/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/graphs-and-transformations/conics/hyperbola/practice",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/02_conics/03_hyperbola/02_practice",
                },
              ],
            },
            {
              name: "Completing the square",
              slug: "/h2_learn/graphs-and-transformations/conics/completing-the-square",
              fileSlug:
                "/h2-1_h2_learn/02_graphs-and-transformations/02_conics/04_completing-the-square",
              children: [
                {
                  name: "Domain restriction",
                  slug: "/h2_learn/graphs-and-transformations/conics/completing-the-square/theory",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/02_conics/04_completing-the-square/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/graphs-and-transformations/conics/completing-the-square/practice",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/02_conics/04_completing-the-square/02_practice",
                },
              ],
            },
          ],
        },
        {
          name: "Transformations",
          slug: "/h2_learn/graphs-and-transformations/transformations",
          fileSlug:
            "/h2-1_h2_learn/02_graphs-and-transformations/03_transformations",
          children: [
            {
              name: "Translation scaling reflection",
              slug: "/h2_learn/graphs-and-transformations/transformations/translation-scaling-reflection",
              fileSlug:
                "/h2-1_h2_learn/02_graphs-and-transformations/03_transformations/01_translation-scaling-reflection",
              children: [
                {
                  name: "Existence of composite functions",
                  slug: "/h2_learn/graphs-and-transformations/transformations/translation-scaling-reflection/theory",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/03_transformations/01_translation-scaling-reflection/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/graphs-and-transformations/transformations/translation-scaling-reflection/practice",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/03_transformations/01_translation-scaling-reflection/02_practice",
                },
              ],
            },
            {
              name: "Modulus",
              slug: "/h2_learn/graphs-and-transformations/transformations/modulus",
              fileSlug:
                "/h2-1_h2_learn/02_graphs-and-transformations/03_transformations/02_modulus",
              children: [
                {
                  name: "Formula and domain of composite functions",
                  slug: "/h2_learn/graphs-and-transformations/transformations/modulus/theory",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/03_transformations/02_modulus/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/graphs-and-transformations/transformations/modulus/practice",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/03_transformations/02_modulus/02_practice",
                },
              ],
            },
            {
              name: "Reciprocal",
              slug: "/h2_learn/graphs-and-transformations/transformations/reciprocal",
              fileSlug:
                "/h2-1_h2_learn/02_graphs-and-transformations/03_transformations/03_reciprocal",
              children: [
                {
                  name: "Range of composite functions",
                  slug: "/h2_learn/graphs-and-transformations/transformations/reciprocal/theory",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/03_transformations/03_reciprocal/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/graphs-and-transformations/transformations/reciprocal/practice",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/03_transformations/03_reciprocal/02_practice",
                },
              ],
            },
            {
              name: "Derivative",
              slug: "/h2_learn/graphs-and-transformations/transformations/derivative",
              fileSlug:
                "/h2-1_h2_learn/02_graphs-and-transformations/03_transformations/04_derivative",
              children: [
                {
                  name: "Self composition",
                  slug: "/h2_learn/graphs-and-transformations/transformations/derivative/theory",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/03_transformations/04_derivative/01_theory",
                },
                {
                  name: "Practice",
                  slug: "/h2_learn/graphs-and-transformations/transformations/derivative/practice",
                  fileSlug:
                    "/h2-1_h2_learn/02_graphs-and-transformations/03_transformations/04_derivative/02_practice",
                },
              ],
            },
          ],
        },
      ],
    },
  ],
};
export const h2_solutionsNav: NavNode = {
  name: "H2_solutions",
  slug: "/h2_solutions",
  fileSlug: "/h2-2_h2_solutions",
  children: [
    {
      name: "2007",
      slug: "/h2_solutions/2007",
      fileSlug: "/h2-2_h2_solutions/2007",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2007/p1",
          fileSlug: "/h2-2_h2_solutions/2007/p1",
          children: [
            {
              name: "Q2",
              slug: "/h2_solutions/2007/p1/q2",
              fileSlug: "/h2-2_h2_solutions/2007/p1/q2",
            },
          ],
        },
      ],
    },
    {
      name: "2008",
      slug: "/h2_solutions/2008",
      fileSlug: "/h2-2_h2_solutions/2008",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2008/p2",
          fileSlug: "/h2-2_h2_solutions/2008/p2",
          children: [
            {
              name: "Q4",
              slug: "/h2_solutions/2008/p2/q4",
              fileSlug: "/h2-2_h2_solutions/2008/p2/q4",
            },
          ],
        },
      ],
    },
    {
      name: "2009",
      slug: "/h2_solutions/2009",
      fileSlug: "/h2-2_h2_solutions/2009",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2009/p2",
          fileSlug: "/h2-2_h2_solutions/2009/p2",
          children: [
            {
              name: "Q3",
              slug: "/h2_solutions/2009/p2/q3",
              fileSlug: "/h2-2_h2_solutions/2009/p2/q3",
            },
          ],
        },
      ],
    },
    {
      name: "2010",
      slug: "/h2_solutions/2010",
      fileSlug: "/h2-2_h2_solutions/2010",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2010/p2",
          fileSlug: "/h2-2_h2_solutions/2010/p2",
          children: [
            {
              name: "Q4",
              slug: "/h2_solutions/2010/p2/q4",
              fileSlug: "/h2-2_h2_solutions/2010/p2/q4",
            },
          ],
        },
      ],
    },
    {
      name: "2011",
      slug: "/h2_solutions/2011",
      fileSlug: "/h2-2_h2_solutions/2011",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2011/p2",
          fileSlug: "/h2-2_h2_solutions/2011/p2",
          children: [
            {
              name: "Q3",
              slug: "/h2_solutions/2011/p2/q3",
              fileSlug: "/h2-2_h2_solutions/2011/p2/q3",
            },
          ],
        },
      ],
    },
    {
      name: "2012",
      slug: "/h2_solutions/2012",
      fileSlug: "/h2-2_h2_solutions/2012",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2012/p1",
          fileSlug: "/h2-2_h2_solutions/2012/p1",
          children: [
            {
              name: "Q7",
              slug: "/h2_solutions/2012/p1/q7",
              fileSlug: "/h2-2_h2_solutions/2012/p1/q7",
            },
          ],
        },
      ],
    },
    {
      name: "2013",
      slug: "/h2_solutions/2013",
      fileSlug: "/h2-2_h2_solutions/2013",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2013/p2",
          fileSlug: "/h2-2_h2_solutions/2013/p2",
          children: [
            {
              name: "Q1",
              slug: "/h2_solutions/2013/p2/q1",
              fileSlug: "/h2-2_h2_solutions/2013/p2/q1",
            },
          ],
        },
      ],
    },
    {
      name: "2014",
      slug: "/h2_solutions/2014",
      fileSlug: "/h2-2_h2_solutions/2014",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2014/p1",
          fileSlug: "/h2-2_h2_solutions/2014/p1",
          children: [
            {
              name: "Q1",
              slug: "/h2_solutions/2014/p1/q1",
              fileSlug: "/h2-2_h2_solutions/2014/p1/q1",
            },
          ],
        },
      ],
    },
    {
      name: "2015",
      slug: "/h2_solutions/2015",
      fileSlug: "/h2-2_h2_solutions/2015",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2015/p2",
          fileSlug: "/h2-2_h2_solutions/2015/p2",
          children: [
            {
              name: "Q3",
              slug: "/h2_solutions/2015/p2/q3",
              fileSlug: "/h2-2_h2_solutions/2015/p2/q3",
            },
          ],
        },
      ],
    },
    {
      name: "2016",
      slug: "/h2_solutions/2016",
      fileSlug: "/h2-2_h2_solutions/2016",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2016/p1",
          fileSlug: "/h2-2_h2_solutions/2016/p1",
          children: [
            {
              name: "Q10",
              slug: "/h2_solutions/2016/p1/q10",
              fileSlug: "/h2-2_h2_solutions/2016/p1/q10",
            },
          ],
        },
      ],
    },
    {
      name: "2017",
      slug: "/h2_solutions/2017",
      fileSlug: "/h2-2_h2_solutions/2017",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2017/p2",
          fileSlug: "/h2-2_h2_solutions/2017/p2",
          children: [
            {
              name: "Q3",
              slug: "/h2_solutions/2017/p2/q3",
              fileSlug: "/h2-2_h2_solutions/2017/p2/q3",
            },
          ],
        },
      ],
    },
    {
      name: "2018",
      slug: "/h2_solutions/2018",
      fileSlug: "/h2-2_h2_solutions/2018",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2018/p1",
          fileSlug: "/h2-2_h2_solutions/2018/p1",
          children: [
            {
              name: "Q5",
              slug: "/h2_solutions/2018/p1/q5",
              fileSlug: "/h2-2_h2_solutions/2018/p1/q5",
            },
          ],
        },
      ],
    },
    {
      name: "2019",
      slug: "/h2_solutions/2019",
      fileSlug: "/h2-2_h2_solutions/2019",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2019/p1",
          fileSlug: "/h2-2_h2_solutions/2019/p1",
          children: [
            {
              name: "Q5",
              slug: "/h2_solutions/2019/p1/q5",
              fileSlug: "/h2-2_h2_solutions/2019/p1/q5",
            },
          ],
        },
      ],
    },
    {
      name: "2021",
      slug: "/h2_solutions/2021",
      fileSlug: "/h2-2_h2_solutions/2021",
      children: [
        {
          name: "P2",
          slug: "/h2_solutions/2021/p2",
          fileSlug: "/h2-2_h2_solutions/2021/p2",
          children: [
            {
              name: "Q3",
              slug: "/h2_solutions/2021/p2/q3",
              fileSlug: "/h2-2_h2_solutions/2021/p2/q3",
            },
          ],
        },
      ],
    },
    {
      name: "2022",
      slug: "/h2_solutions/2022",
      fileSlug: "/h2-2_h2_solutions/2022",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2022/p1",
          fileSlug: "/h2-2_h2_solutions/2022/p1",
          children: [
            {
              name: "Q6",
              slug: "/h2_solutions/2022/p1/q6",
              fileSlug: "/h2-2_h2_solutions/2022/p1/q6",
            },
          ],
        },
      ],
    },
    {
      name: "2023",
      slug: "/h2_solutions/2023",
      fileSlug: "/h2-2_h2_solutions/2023",
      children: [
        {
          name: "P1",
          slug: "/h2_solutions/2023/p1",
          fileSlug: "/h2-2_h2_solutions/2023/p1",
          children: [
            {
              name: "Q7",
              slug: "/h2_solutions/2023/p1/q7",
              fileSlug: "/h2-2_h2_solutions/2023/p1/q7",
            },
          ],
        },
      ],
    },
  ],
};
export const h2_tys_questionsNav: NavNode = {
  name: "H2_tys_questions",
  slug: "/h2_tys_questions",
  fileSlug: "/h2-3_h2_tys_questions",
  children: [
    {
      name: "2007",
      slug: "/h2_tys_questions/2007",
      fileSlug: "/h2-3_h2_tys_questions/2007",
      children: [
        {
          name: "P1",
          slug: "/h2_tys_questions/2007/p1",
          fileSlug: "/h2-3_h2_tys_questions/2007/p1",
          children: [
            {
              name: "Q2",
              slug: "/h2_tys_questions/2007/p1/q2",
              fileSlug: "/h2-3_h2_tys_questions/2007/p1/q2",
            },
          ],
        },
      ],
    },
  ],
};
export const h2_learnSequential: { name: string; slug: string }[] = [
  {
    name: "Describing sets of real numbers",
    slug: "/h2_learn/functions/concepts/intervals/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/concepts/intervals/practice" },
  {
    name: "Functions, domain and range",
    slug: "/h2_learn/functions/concepts/domain-and-range/theory",
  },
  {
    name: "Practice 1",
    slug: "/h2_learn/functions/concepts/domain-and-range/practice-1",
  },
  {
    name: "Practice 2",
    slug: "/h2_learn/functions/concepts/domain-and-range/practice-2",
  },
  {
    name: "Existence of inverse functions",
    slug: "/h2_learn/functions/inverse/existence/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/inverse/existence/practice" },
  {
    name: "Domain and range of inverse functions",
    slug: "/h2_learn/functions/inverse/domain/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/inverse/domain/practice" },
  {
    name: "Formula of inverse functions",
    slug: "/h2_learn/functions/inverse/formula/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/inverse/formula/practice" },
  {
    name: "Domain restriction",
    slug: "/h2_learn/functions/inverse/restriction/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/functions/inverse/restriction/practice",
  },
  {
    name: "Relationship between a function and its inverse",
    slug: "/h2_learn/functions/inverse/relationship/theory",
  },
  {
    name: "Practice 1",
    slug: "/h2_learn/functions/inverse/relationship/practice-1",
  },
  {
    name: "Practice 2",
    slug: "/h2_learn/functions/inverse/relationship/practice-2",
  },
  {
    name: "Existence of composite functions",
    slug: "/h2_learn/functions/composite/existence/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/functions/composite/existence/practice",
  },
  {
    name: "Formula and domain of composite functions",
    slug: "/h2_learn/functions/composite/formula/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/composite/formula/practice" },
  {
    name: "Range of composite functions",
    slug: "/h2_learn/functions/composite/range/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/composite/range/practice" },
  {
    name: "Self composition",
    slug: "/h2_learn/functions/composite/self-compose/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/functions/composite/self-compose/practice",
  },
  {
    name: "Composing inverse functions",
    slug: "/h2_learn/functions/composite/compose-inverse/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/functions/composite/compose-inverse/practice",
  },
  {
    name: "Self-inverse functions",
    slug: "/h2_learn/functions/more/self-inverse/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/more/self-inverse/practice" },
  {
    name: "Piecewise functions",
    slug: "/h2_learn/functions/more/piecewise/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/more/piecewise/practice" },
  {
    name: "Modulus functions",
    slug: "/h2_learn/functions/more/modulus/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/more/modulus/practice" },
  {
    name: "Using the quadratic discriminant",
    slug: "/h2_learn/functions/more/discriminant/theory",
  },
  { name: "Practice", slug: "/h2_learn/functions/more/discriminant/practice" },
  {
    name: "Asymptotes",
    slug: "/h2_learn/graphs-and-transformations/standard-graphs/asymptotes/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/graphs-and-transformations/standard-graphs/asymptotes/practice",
  },
  {
    name: "Rational functions",
    slug: "/h2_learn/graphs-and-transformations/standard-graphs/rational-functions/theory",
  },
  {
    name: "Practice 1",
    slug: "/h2_learn/graphs-and-transformations/standard-graphs/rational-functions/practice-1",
  },
  {
    name: "Practice 2",
    slug: "/h2_learn/graphs-and-transformations/standard-graphs/rational-functions/practice-2",
  },
  {
    name: "Oblique asymptotes",
    slug: "/h2_learn/graphs-and-transformations/standard-graphs/oblique-asymptotes/theory",
  },
  {
    name: "Practice 1",
    slug: "/h2_learn/graphs-and-transformations/standard-graphs/oblique-asymptotes/practice-1",
  },
  {
    name: "Practice 2",
    slug: "/h2_learn/graphs-and-transformations/standard-graphs/oblique-asymptotes/practice-2",
  },
  {
    name: "Functions, domain and range",
    slug: "/h2_learn/graphs-and-transformations/standard-graphs/more/theory",
  },
  {
    name: "Practice 1",
    slug: "/h2_learn/graphs-and-transformations/standard-graphs/more/practice-1",
  },
  {
    name: "Practice 2",
    slug: "/h2_learn/graphs-and-transformations/standard-graphs/more/practice-2",
  },
  {
    name: "Existence of inverse functions",
    slug: "/h2_learn/graphs-and-transformations/conics/introduction/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/graphs-and-transformations/conics/introduction/practice",
  },
  {
    name: "Domain and range of inverse functions",
    slug: "/h2_learn/graphs-and-transformations/conics/ellipses/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/graphs-and-transformations/conics/ellipses/practice",
  },
  {
    name: "Formula of inverse functions",
    slug: "/h2_learn/graphs-and-transformations/conics/hyperbola/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/graphs-and-transformations/conics/hyperbola/practice",
  },
  {
    name: "Domain restriction",
    slug: "/h2_learn/graphs-and-transformations/conics/completing-the-square/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/graphs-and-transformations/conics/completing-the-square/practice",
  },
  {
    name: "Existence of composite functions",
    slug: "/h2_learn/graphs-and-transformations/transformations/translation-scaling-reflection/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/graphs-and-transformations/transformations/translation-scaling-reflection/practice",
  },
  {
    name: "Formula and domain of composite functions",
    slug: "/h2_learn/graphs-and-transformations/transformations/modulus/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/graphs-and-transformations/transformations/modulus/practice",
  },
  {
    name: "Range of composite functions",
    slug: "/h2_learn/graphs-and-transformations/transformations/reciprocal/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/graphs-and-transformations/transformations/reciprocal/practice",
  },
  {
    name: "Self composition",
    slug: "/h2_learn/graphs-and-transformations/transformations/derivative/theory",
  },
  {
    name: "Practice",
    slug: "/h2_learn/graphs-and-transformations/transformations/derivative/practice",
  },
];
export const h2_solutionsSequential: { name: string; slug: string }[] = [
  { name: "Q2", slug: "/h2_solutions/2007/p1/q2" },
  { name: "Q4", slug: "/h2_solutions/2008/p2/q4" },
  { name: "Q3", slug: "/h2_solutions/2009/p2/q3" },
  { name: "Q4", slug: "/h2_solutions/2010/p2/q4" },
  { name: "Q3", slug: "/h2_solutions/2011/p2/q3" },
  { name: "Q7", slug: "/h2_solutions/2012/p1/q7" },
  { name: "Q1", slug: "/h2_solutions/2013/p2/q1" },
  { name: "Q1", slug: "/h2_solutions/2014/p1/q1" },
  { name: "Q3", slug: "/h2_solutions/2015/p2/q3" },
  { name: "Q10", slug: "/h2_solutions/2016/p1/q10" },
  { name: "Q3", slug: "/h2_solutions/2017/p2/q3" },
  { name: "Q5", slug: "/h2_solutions/2018/p1/q5" },
  { name: "Q5", slug: "/h2_solutions/2019/p1/q5" },
  { name: "Q3", slug: "/h2_solutions/2021/p2/q3" },
  { name: "Q6", slug: "/h2_solutions/2022/p1/q6" },
  { name: "Q7", slug: "/h2_solutions/2023/p1/q7" },
];
export const h2_tys_questionsSequential: { name: string; slug: string }[] = [
  { name: "Q2", slug: "/h2_tys_questions/2007/p1/q2" },
];
export const nav = [h2_learnNav, h2_solutionsNav, h2_tys_questionsNav];
export const sequentialNav = [
  ...h2_learnSequential,
  ...h2_solutionsSequential,
  ...h2_tys_questionsSequential,
];
